disabled_rules:
  - file_length
  - line_length
  - identifier_name
  - todo # Enabled this again!
  - vertical_whitespace
  - force_cast
  - force_try
  - large_tuple
  - function_body_length
  - nesting # Disabled because of https://github.com/realm/SwiftLint/issues/1151
  - type_body_length
opt_in_rules:
  - empty_count
  - prohibited_super_call
  - conditional_returns_on_newline
  - implicit_return
  - overridden_super_call
  - private_outlet
  - redundant_nil_coalescing
  - first_where
  - explicit_init
  - switch_case_on_newline
  - number_separator
  - closure_end_indentation
  - closure_spacing
  - operator_usage_whitespace
  - nimble_operator
  - attributes
  - fatal_error_message
  - unneeded_parentheses_in_closure_argument
  - trailing_closure
  - block_based_kvo
  - discouraged_direct_init
  - joined_default_parameter
  - pattern_matching_keywords
  - contains_over_first_not_nil
  - fallthrough
  - array_init
  - literal_expression_end_indentation
  - sorted_first_last
  - private_action
  - yoda_condition
  - required_enum_case
  - discouraged_optional_boolean
  - empty_string
  - untyped_error_in_catch
  - discouraged_optional_collection
  - modifier_order
  - unavailable_function
  - multiline_function_chains
  - redundant_set_access_control
  - empty_xctest_method
  - multiline_arguments
  - anyobject_protocol
  - redundant_type_annotation
  - no_extension_access_modifier
force_cast: warning
force_unwrapping: warning
number_separator:
  minimum_length: 5
